config/routes.rb
Rails.application.routes.draw do
 
  root  "home#index"

  namespace :admin do
    #usuarios
    get '/users', to: 'user#index', as: 'users'
    get '/users/create', to: 'user#create', as: 'users_create'
    post '/users/store', to: 'user#store', as: 'users_store'
    get '/users/edit/:id', to: 'user#edit', as: 'users_edit'
    post '/users/update/:id', to: 'user#update', as: 'users_update'
    get '/users/delete/:id', to: 'user#delete', as: 'users_delete'
  end
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/admin/user_controller.rb
class Admin::UserController < ApplicationController
    def index
        @users = User.all
      end
    
      def create
        @user = User.new
      end
    
      def store
        @user = User.new(user_params)
        if @user.save
          redirect_to admin_users_path, notice: "User was successfully created."
        else
          render :new
        end
      end
    
      def edit
        @user = User.find(params[:id])
      end
    
      def update
        @user = User.find(params[:id])
        if @user.update(user_params)
          redirect_to admin_users_path, notice: "User was successfully updated."
        else
          render :edit
        end
      end
    
      def delete
        @user = User.find(params[:id])
        @user.destroy
        redirect_to users_path, notice: "User was successfully deleted."
      end
    
      private
    
      def user_params
        params.require(:user).permit(:name, :email, :password_digest)
      end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    def index
        
    end
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/admin/user/create.html.erb
<form action="/admin/users/store" method="post">
<input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
<div class="mb-3">
    <label class="form-label">Cliente</label>
    <input type="text" class="form-control"  name="user[name]">
  </div>
  <div class="mb-3">
    <label class="form-label">Email</label>
    <input type="email" class="form-control"  name="user[email]">
  </div>
  <div class="mb-3">
    <label class="form-label">Password</label>
    <input type="password" class="form-control" name="user[password_digest]">
  </div>
  
  <button type="submit" class="btn btn-primary">Submit</button>
</form>

app/views/admin/user/edit.html.erb
editar

app/views/admin/user/index.html.erb
<h1 class="text-primary text-center m-4 fw-bold">Lista de usuarios </h1>

<button  class="btn btn-success m-4 "><%= link_to "Crear usuario", admin_users_create_path%></button>
<br>



<table class="table">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Nombre</th>
      <th scope="col">Email</th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
    <tr>
      <th scope="row">1</th>
      <td><%= user.name %></td>
      <td><%= user.email %></td>     
    </tr>
     <% end %>
  </tbody>
</table>

app/views/home/index.html.erb
<h1 class="text-danger"> Home sdsd<h1>
<p> Fdsdsds  in app/views/home/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TourismProjectsss</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
 
    <%= yield %>
  </body>
</html>